### ISSUE TITLE
[M] Public - Passes sold out message

### ISSUE THREAD

**Issue by Dianadec** [bcgov/parks-reso-public#335] opened 2024-04-04 21:27 UTC
#### Description:
As a park visitor I want to be made aware when passes are sold out so that I know why I can't book a pass.

#### Acceptance Criteria:

Given that I am a potential park visitor
When I click to reserve a DUP at the same time as someone else and there are no more passes available
then I see a "Sold out" message.

#### Development Checklist:

- [ ] Look into pub/sub for updating the UI automatically instead of waiting for the user to click `Reserve` This way we can grey out the button in near realtime.
- [ ] Sold out message is a toast
- [ ] user selects visit date, pass type and booking time
- [ ] user clicks reserve
- [ ] when another users has been quicker to select these exact passes and their are no reserveable passes left a warning will display on the top of the screen
- [ ] Toast Text reads: bold url stuff then: Sorry, all passes for this time and date have been reserved. Please make a new selection or try again later. 
- [ ] Clicking OK on toast will remove warning from page
- [ ] user will remain on parks book a pass page
- [ ] all fields will be cleared of previous selections

Figma link https://www.figma.com/file/2lQW8InOa0lEiUiMeGmeNC/Day-Use-Pass?type=design&node-id=4074%3A6376&mode=design&t=YbmeWNjWNn9tCaMc-1

#### Dependencies

- Blocked by https://github.com/bcgov/parks-reso-api/issues/358 
and https://github.com/bcgov/parks-reso-public/issues/329
- Blocking

**Wireframe(s):**

**Workflows:**

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [x] User story is included
- [x] User role and type are identified
- [x] Acceptance criteria are included
- [x] Wireframes are included
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** 
- In progress:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] UI meets accessibility requirements
  - [ ] Unit tests are written
  - [ ] Work is traceable in GitHub
  - [ ] PR linked to ticket number
  - [ ] If needed/required - Dev adds flag/label to highlight any migration steps necessary prior to PROD deployment
- Code review:
  - [ ] Code is peer reviewed and has passed CI/CD tests
- QA:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Code is potentially shippable to the production environment
  - [ ] Functional features have been tested and passed by QA
  - [ ] UI components tested by designer
  - [ ] Code is deployed to PROD when moved to 'done' column (unless requested otherwise by PO)
- PO Review:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Reviewed and approved by Product Owner

#### Notes:
- 
-

**Comment by manuji** [comment] 2024-05-27 17:34
Tested on TEST: **Failed**
* I was able to concurrently book the one last pass successfully. 
* For some reason I did not get the booking confirmation for both attempts. 

Scenario:
* Navigate to the DUP public on TES.
* Select the park Mount seymour
* Pick a date and pick the trail facility.
* Simultaneously from two devices, try to book the pass. 



![Image](https://github.com/bcgov/parks-reso-public/assets/65190263/6da25c71-b6d0-4053-820e-29df9be87432)

**Comment by manuji** [comment] 2024-05-28 17:57
Tested on TEST: **Passed**
* verified that when concurrent attempts to book the last pass, only one user succeeds and other users get's a user message with an error. 
* Passing to PO review.

**Comment by meyerdarcie** [comment] 2024-05-28 19:21
Working as intended - moving to done.

**Closed by meyerdarcie** 2024-05-28 19:21 UTC
Labels: DUP
