### ISSUE TITLE
[L] Public - DUP is held during booking process

### ISSUE THREAD

**Issue by JLWade** [bcgov/parks-reso-public#330] opened 2024-03-27 19:21 UTC
As a park visitor, I want to have confidence that if there are passes available when I start booking a DUP that I will be able to successfully book one. 

#### Description:
One of the biggest pieces of feedback we get on DUP is that people try to book a pass and before they enter all their info and submit all the passes are sold out. Being able to hold your pass while you book for a specific amount of time would be ideal.

#### Acceptance Criteria:

Given I am a potential park visitor
When I am on the booking page and select my booking date, facility, time and click **`Reserve`**
Then I know my pass is "held" for me for 5 minutes or until I complete my booking within 5 minutes.

Given I am a potential park visitor
When I am filling out my information on the contact page
Then I can see how much time I have to complete my booking before my pass goes back into the booking pool. [5 minutes]

- [x] user selects visit date and pass type then clicks reserve
- [x] Clicking `Reserve` initiates an attempt to hold a pass, if successful, show the checkout screen. Otherwise 'no passes left'
- [x] After clicking reserve, the hold timer will display at the top of the contact information page
- [x] Timer will immediately begin counting down 5 minute allotted time
- [ ] Timer is sticky and will remain in view as user scrolls down the page filling in contact information
- [x] Timer will include text to identify pass is being held for the allotted time (5 minutes, then we'll see what feedback we get)

#### Development Checklist:

- [ ] Change button to say `Reserve`

#### Dependencies

- Blocked by https://github.com/bcgov/parks-reso-api/issues/358
- Blocked by #329 

**Wireframe(s):**
- [Desktop](https://www.figma.com/file/2lQW8InOa0lEiUiMeGmeNC/Day-Use-Pass?type=design&node-id=4299-13811&mode=design&t=9vvZOwIx6S2DTXvt-4)
- [Mobile](https://www.figma.com/file/2lQW8InOa0lEiUiMeGmeNC/Day-Use-Pass?type=design&node-id=4299-13986&mode=design&t=9vvZOwIx6S2DTXvt-4)

icon: `exclamation-circle-fill`
background: `#FEF1D8`
text: `#7E5D21`

**Workflows:**

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [x] User story is included
- [x] User role and type are identified
- [x] Acceptance criteria are included
- [x] Wireframes are included
- [ ] Design / Solution is accepted by Product Owner
- [x] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** 
- In progress:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] UI meets accessibility requirements (ensure timer is tagged properly for screen readers)
  - [ ] Unit tests are written
  - [ ] Work is traceable in GitHub
  - [ ] PR linked to ticket number
  - [ ] If needed/required - Dev adds flag/label to highlight any migration steps necessary prior to PROD deployment
- Code review:
  - [ ] Code is peer reviewed and has passed CI/CD tests
- QA:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Code is potentially shippable to the production environment
  - [ ] Functional features have been tested and passed by QA
  - [ ] UI components tested by designer
  - [ ] Code is deployed to PROD when moved to 'done' column (unless requested otherwise by PO)
- PO Review:
  - [ ] Acceptance criteria are tested (Functionality meets the acceptance criteria defined in the ticket)
  - [ ] Reviewed and approved by Product Owner

#### Notes:
- 
-

**Comment by Dianadec** [comment] 2024-04-16 17:32
Developer checklist added during refinement - starting with the simplest way to start.

**Comment by JLWade** [comment] 2024-04-18 17:01
Blocked until designs are added

**Comment by manuji** [comment] 2024-05-27 17:00
Tested on TEST: **Passed**
* verified that if a user has started the booking process then that pass is held unless it's cancelled for 7 minutes. 
* Passing to PO review. 
Issues related this feature have been reported under: https://github.com/bcgov/parks-reso-public/issues/334.

**Comment by meyerdarcie** [comment] 2024-05-27 22:57
Working as intended - moving to done. 

@cameronpettit - I'm curious about the sticky function listed in the acceptance criteria, something to discuss and make a ticket around if necessary.

**Closed by meyerdarcie** 2024-05-27 22:57 UTC
Labels: DUP

**Comment by cameronpettit** [comment] 2024-05-28 16:07
Sticky timer bar implemented.

**Comment by manuji** [comment] 2024-05-28 17:40
Tested on TEST: **Passed**
* verified that the sticky banner has been implemented. 
* Passing to PO review.

**Comment by meyerdarcie** [comment] 2024-05-28 17:49
Timer is now sticky - operating as intended, moving to done.
